kind: Pod
apiVersion: v1
metadata:
  name: security-context-pod
spec:
  securityContext:
    # User ID that containers in this pod should run as
    runAsUser: 45
    # Group ID for filesystem access
    fsGroup: 231
  volumes:
    - name: simple-directory
      emptyDir: {}
  containers:
    - name: example-container
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /etc/directory/file.txt; sleep 5; done"]
      volumeMounts:
        - name: simple-directory
          mountPath: 
# kubectl apply -f security-context.yaml
# pod "security-context-pod" created
# kubectl exec security-context-pod -- ls -l /etc/directory
# -rw-r--r-- 1 45 231 58 Jul 3 09:45 file.txt
# kubectl exec security-context-pod -- cat /etc/directory/file.txt